### ISSUE TITLE
Script to remove duplicate quotes

### ISSUE THREAD

**Issue by mubaris** [mubaris/motivate#20]
Add a small script to automatically delete all the duplicate quotes in the `data` folder.

**Comment by michellymenezes** [comment]
Is it to remove duplicated quotes in an unique file or among all files? Is the script allowed to edit the files in data folder?

**Comment by mubaris** [comment]
We want to remove duplicate quotes from all the json files in `data` folder. We already have a script to find duplicate entries. That script will be useful.

Yes, the script is allowed to edit the files in `data` folder. Whenever there's a duplicate entry in json file, it should be removed.

**Comment by charlottetan** [comment]
Doesn't `find_dupes.py` already find them?

**Comment by michellymenezes** [comment]
Ok. I'll take this issue.

**Comment by michellymenezes** [comment]
Can't run `$ motivate` 

> TypeError: join() argument must be str or bytes, not 'PosixPath'

**Comment by mubaris** [comment]
@michellymenezes I think I have fixed this issue. Let me know if there's any problem. Clone and install again

**Comment by michellymenezes** [comment]
@mubaris I've made a script to create a new json file with all unique quotes #25

**Comment by mubaris** [comment]
@michellymenezes It would be very useful instead creating new json file, if we could remove the entry from existing json files.

**Comment by Souvikray** [comment]
Can I take this up?

**Comment by mubaris** [comment]
There's already a PR. There's a small problem with it. If you can find a method to eliminate that issue, let me know.

**Comment by Souvikray** [comment]
What's the problem?

**Comment by mubaris** [comment]
Check #25

**Comment by Souvikray** [comment]
Hey in your find_dupes.py file,can you explain me in this line of code
dupes = sorted([x for x in quotes if x['quote'] in seen or seen.add(x['quote'])], key=lambda x:x['quote'])
What do the 'key=lambda x:x['quote']' does?

**Comment by michellymenezes** [comment]
@mubaris I think removing repeated quotes from each file will cost more than computing unique quotes and getting everything from a unique file.

**Comment by Souvikray** [comment]
@mubaris Hey is the issue still open?I made a fix for what you want to achieve.

**Comment by wimo7083** [comment]
https://github.com/mubaris/motivate/pull/40

Issue was still open, you mentioned there were issues with previous implementation. In this case it's better to not worry about cost, but worry about ease of the database. Maintaining multiple json files only makes sense if there is a difference between them (001 = science quotes, 002 = history quotes, 007 = james bond quotes). If you wish for randomization it'll be easier if you don't have to randomize file in addition to the quote. 

If you'd like I can do the same refactoring to your same quote as this one. It ends up improving readability.
