### ISSUE TITLE
Cannot install - "This script must be with sudo"

### ISSUE THREAD

**Issue by EveChen** [mubaris/motivate#21]
Sorry to spam this board, but I really hope to install **motivate** into my Macbook (using terminal). The problem I encountered is, the terminal always telling me "This script must be with sudo" when I executed the `./install.sh` command.
![image](https://user-images.githubusercontent.com/11646036/31596932-62d889a0-b1fa-11e7-9064-ade97c3d4b76.png)

I tried to solve this and I did read some of the related posts from Slackoverflow, but still failed. 
For example, I ran sudo `./install.sh` and it returned 
![image](https://user-images.githubusercontent.com/11646036/31597159-c168b50c-b1fb-11e7-8e26-29358cef4196.png)

<The codes I tried>
`sh install.sh` : Failed. Return "This script must be with sudo".

`chmod +x install.sh` and then `./install.sh` : Failed. Return "This script must be with sudo".

*I also double checked if I'm in the right directory but still could not install. Hope to have any help! Thank you! :)
![image](https://user-images.githubusercontent.com/11646036/31597231-2e0cd544-b1fc-11e7-9d6e-25bfbc861d39.png)

*Other Info
Macbook Pro, macOS Sierra version 10.12.6

**Comment by mubaris** [comment]
I think I have fixed this issue. Clone it again and try it. Let know if there's any problem.

**Comment by EveChen** [comment]
@mubaris Thanks a lot! I can install it now. :)
