### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by AlecRust** [mubaris/motivate#39]
The README doesn't line up with the contents of the repo due to recent changes, could it be updated?

I got notified of a new release, but cloning and following the instructions fresh no longer work.

**Comment by mubaris** [comment]
We need to change README. But installing PyPi is not working.

If you can, send PR for README fix. If possible can you check PyPi issue?

**Comment by fossterer** [comment]
The instructions work fine for me on Ubuntu. I see only the 'UPDATE' instruction is not usable. Is that what should be edited out?
