### ISSUE TITLE
Add support for Fish and other shells

### ISSUE THREAD

**Issue by mubaris** [mubaris/motivate#4]

**Comment by jmhobbs** [comment]
What are some other shells you're looking for?

**Comment by mubaris** [comment]
Kshell and xonsh

**Comment by f-breidenstein** [comment]
Why you don't just copy the motivation.py to somewhere like /usr/local/bin?
This would require sudo for the copy process but then it would directly in the $PATH for every user and the install script does not have to be changed for every single shell

**Comment by mubaris** [comment]
@f-breidenstein Got the PR. Closing this issue.
