### ISSUE TITLE
ANSI colour codes don't work in (newer) Windows 10 command line

### ISSUE THREAD

**Issue by LucyParry** [mubaris/motivate#58]
Firstly - Hello and nice project!

I have a query however - Unfortunately the method of using ANSI escape sequences to colour the output doesn't seem to work in all cases on Windows 10. I'm running Windows 10 Home, Version 1703, Build 15063.674 and the output includes parts of the escape strings printed with the quote like this -

![motivate_before](https://user-images.githubusercontent.com/12956949/32070251-b339ba2c-ba83-11e7-9508-62fd64e734a0.PNG)

I may be doing something wrong (?) but from what I can gather from [this](https://stackoverflow.com/questions/44047988/windows-10-console-colors-not-working-virtual-terminal-control-character-sequen) and [this](https://github.com/symfony/symfony/issues/19520) the feature was available briefly but then removed by default, and as far as I can see there is no straightforward way to colour individual lines of text output (without further configuration or an external tool), although others may know better?

A simple way to at least get the quotes looking nice is to use `platform.system()` to test if the OS is Windows, and then not include the colour sequences if it is, so the output looks like this -
 
![motivate_after](https://user-images.githubusercontent.com/12956949/32070468-59eed9e2-ba84-11e7-9ff2-c57d241c4b0e.PNG)

I have tried this on my own fork so will submit a PR if anyone wants it? :)

**Comment by mubaris** [comment]
Will look into it

**Comment by LucyParry** [comment]
Thank you that's great. Have submitted the 'workaround' but if someone can fix it properly it would be good to learn how to do it!

**Comment by mubaris** [comment]
Cool, I think your PR will work. Closing this now.
